parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"kIKx":[function(require,module,exports) {
"use strict";var C;Object.defineProperty(exports,"__esModule",{value:!0}),exports.PriceIndication=void 0,function(C){C.CURRENCY_SYMBOL="€",C.CURRENCY_PREFIX_UC="EUR",C.CURRENCY_PREFIX_LC="eur",C.CURRENCY_PREFIX_CC="Eur",C.CURRENCY_NAME_CC="Euro",C.CURRENCY_NAME_LC="euro",C.CURRENCY_NAME_UC="EURO"}(C=exports.PriceIndication||(exports.PriceIndication={}));
},{}],"Gu2M":[function(require,module,exports) {
"use strict";var e;Object.defineProperty(exports,"__esModule",{value:!0}),exports.Flag=void 0,function(e){e.CLASS_EXCLUDE_ITEM="pit-exclude",e.WHITESPACE=" "}(e=exports.Flag||(exports.Flag={}));
},{}],"CNkU":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.DomExtract=void 0;var e=require("./enums/price-indication"),i=require("./enums/flag"),t=function(){function t(e){void 0===e&&(e="*"),this.filter=Array.prototype.filter,this.domNodes=document.querySelectorAll(e)}return t.prototype.getTextNodes=function(){return console.log("Init extraction"),this.filter.call(this.domNodes,function(t){var n=t.childNodes[0];if(!!n&&"string"==typeof n.nodeValue){var r=n.nodeValue;return-1===t.className.indexOf(i.Flag.CLASS_EXCLUDE_ITEM)&&(-1!==r.indexOf(e.PriceIndication.CURRENCY_SYMBOL)||-1!==r.indexOf(e.PriceIndication.CURRENCY_PREFIX_UC)||-1!==r.indexOf(e.PriceIndication.CURRENCY_PREFIX_CC)||-1!==r.indexOf(e.PriceIndication.CURRENCY_PREFIX_LC)||-1!==r.indexOf(e.PriceIndication.CURRENCY_NAME_CC)||-1!==r.indexOf(e.PriceIndication.CURRENCY_NAME_LC)||-1!==r.indexOf(e.PriceIndication.CURRENCY_NAME_UC))}return!1})},t}();exports.DomExtract=t;
},{"./enums/price-indication":"kIKx","./enums/flag":"Gu2M"}],"iBZp":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./dom-extract"),t=require("./enums/flag");console.log("PIT RUNNING");var n=function(){document.querySelectorAll(".pithidden").forEach(function(e){e.className=e.className.replace("pithidden","")})},a=0,i=!1,r='<div class="pitheader"><button id="showPitPricesBtn">Zeige PIT-Preise</button></div>';setInterval(function(){if(a>0&&!i){document.getElementsByTagName("body")[0];i=!0,requestAnimationFrame(function(){document.getElementById("showPitPricesBtn").addEventListener("click",n)})}(new e.DomExtract).getTextNodes().forEach(function(e){var n=e.childNodes[0].nodeValue.replace(/[^0-9,]/g,"").replace(/,/g,"."),i=parseInt(n,10);if("number"==typeof i){var r=(.97*i).toFixed(2);e.className+=t.Flag.WHITESPACE+t.Flag.CLASS_EXCLUDE_ITEM,e.innerHTML+=' <span class="pitprice '+t.Flag.CLASS_EXCLUDE_ITEM+'">PITPRICE* ~'+r+"EUR </span>",a+=1}})},1e3);var c=function(){};
},{"./dom-extract":"CNkU","./enums/flag":"Gu2M"}]},{},["iBZp"], null)
//# sourceMappingURL=/pit.e731e373.js.map